### PR TITLE
 [UPD] title

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
It's rare you get the InvalidCommandError because
Selection_167.

It looks like you didn't deploy the rebase_bot PR 🤔

**Comment by legalsylvain** [comment]
@MiquelRForgeFlow Thanks for your review ! 

Indeed, there was a bug in my knowledge of Docker ;-)
Seems fixed ! 

However, I have this message 

``fatal: could not read Username for 'https://github.com': No such device or address``. 

The url seems valid in the command : ``git push --force https://github.com/legalsylvain/github-ocabot-test.git tmp-pr-15:12.0-REF-title``. 

do you think the ``rebase`` command requires extra configuration ? 

thanks !

**Comment by MiquelRForgeFlow** [comment]
The error has to do with the authentication prompt. I added the github token, hope it's solved now.

**Comment by legalsylvain** [comment]
> The error has to do with the authentication prompt. I added the github token, hope it's solved now.

thanks for the follow up ! 

I'll test again and give your feedback.

have a nice day.

**Pull request closed without merging**
