### PR TITLE
Update __manifest__.py

### PR DESCRIPTION
**Pull request by github-grap-bot-ngrok-dev**
## Ticket:

- apps/deck/#/board/144/card/XXX

## Changes proposed in this pull request:

-
-
-

CC : @grap/service-informatique

### CODE REVIEW

**Review by github-grap-bot-ngrok-dev — COMMENTED** [review]
/ocabot merge patch

**Review by legalsylvain — COMMENTED** [review]
/ocabot merge patch

**Review by legalsylvain — COMMENTED** [review]
/ocabot merge coincoin

**Review by legalsylvain — COMMENTED** [review]
/ocabot merge coucou

**Review by legalsylvain — COMMENTED** [review]
/ocabot merge fromage

**Comment by github-grap-bot-ngrok-dev** [comment]
Hi @legalsylvain. Your command failed:

``Invalid options for command merge: fromage2``.

**Ocabot commands**
* ``ocabot merge major|minor|patch|nobump``
* ``ocabot rebase``

**More information**
 * [ocabot documentation](https://github.com/OCA/oca-github-bot/#commands)
 * [OCA guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst), specially the "Version Numbers" section.

**Review by legalsylvain — COMMENTED** [review]
/ocabot merge coucou

**Comment by github-grap-bot-ngrok-dev** [comment]
Hi @legalsylvain. Your command failed:

``Invalid options for command merge: test``.

**Ocabot commands**
* ``ocabot merge major|minor|patch|nobump``
* ``ocabot rebase``

**More information**
 * [ocabot documentation](https://github.com/OCA/oca-github-bot/#commands)
 * [OCA guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst), specially the "Version Numbers" section.

**Comment by github-grap-bot-ngrok-dev** [comment]
Hi @legalsylvain. Your command failed:

``Invalid command: megegege``.

**Ocabot commands**
* ``ocabot merge major|minor|patch|nobump``
* ``ocabot rebase``

**More information**
 * [ocabot documentation](https://github.com/OCA/oca-github-bot/#commands)
 * [OCA guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst), specially the "Version Numbers" section.

**Review by legalsylvain — COMMENTED** [review]
/ocabot coucoucoucou

**Comment by github-grap-bot-ngrok-dev** [comment]
Hi @legalsylvain. Your command failed:

``Invalid command: qqsdfqsdfqsddfsqfsd``.

**Ocabot commands**
* ``ocabot merge major|minor|patch|nobump``
* ``ocabot rebase``

**More information**
 * [ocabot documentation](https://github.com/OCA/oca-github-bot/#commands)
 * [OCA guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst), specially the "Version Numbers" section.

**Review by legalsylvain — COMMENTED** [review]
/ocabot BY REVIEW CHANGES !!!

**Comment by github-grap-bot-ngrok-dev** [comment]
Hi @legalsylvain. Your command failed:

``Invalid command: BY``.

**Ocabot commands**
* ``ocabot merge major|minor|patch|nobump``
* ``ocabot rebase``

**More information**
 * [ocabot documentation](https://github.com/OCA/oca-github-bot/#commands)
 * [OCA guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst), specially the "Version Numbers" section.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
@legalsylvain The merge process could not start, because of exception name '_logger' is not defined.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
@legalsylvain The merge process could not start, because of exception name 'addon_dirs' is not defined.

**Comment by github-grap-bot-ngrok-dev** [comment]
@legalsylvain The merge process could not start, because of exception 'str' object cannot be interpreted as an integer.

**Comment by github-grap-bot-ngrok-dev** [comment]
@legalsylvain The merge process could not start, because of exception 'str' object cannot be interpreted as an integer.

**Comment by github-grap-bot-ngrok-dev** [comment]
@legalsylvain The merge process could not start, because of exception 'str' object cannot be interpreted as an integer.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
@legalsylvain The merge process could not start, because of exception name 'addon' is not defined.

**Comment by github-grap-bot-ngrok-dev** [comment]
@legalsylvain The merge process could not start, because of exception name 'modules' is not defined.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
Sorry @legalsylvain you are not allowed to merge.

To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.

If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

**Comment by github-grap-bot-ngrok-dev** [comment]
This PR looks fantastic, let's merge it!
Prepared branch [12.0-ocabot-merge-pr-25-by-legalsylvain-bump-patch](https://github.com/grap/github-ocabot-test/commits/12.0-ocabot-merge-pr-25-by-legalsylvain-bump-patch), awaiting test results.

**Comment by github-grap-bot-ngrok-dev** [comment]
Congratulations, your PR was merged at d7dfcb6cc133a144954cdcec33b6590b463768f7. Thanks a lot for contributing to grap. ❤️

**Pull request merged**
